language: r
sudo: false
cache: packages
warnings_are_errors: false
matrix:
  include:
  - os: linux
    r: release
    
  - os: linux
    r: oldrel
    after_success:
    - echo skipping source packaging on linux/oldrel
    
  - os: linux
    r: devel
    after_success:
    - echo skipping source packaging on linux/devel
    
  - os: osx
    r: release
    if: branch = master
    r_github_packages:
    - DeclareDesign/DDtools
    - ropensci/git2r


  - os: osx
    osx_image: xcode6.4
    r: oldrel
    if: branch = master
    r_github_packages:
    - DeclareDesign/DDtools
    - ropensci/git2r

env:
  global:
  - OS=$(uname -s)
  - secure: refD1JbQWIB1CkFCwrfjuUM8xn/Fa55O44/lQpn0347elIPp2S4iFndGL+NBb99YIBExrwuK+sOdmETvsH5csDBdkxvtvcJkSjCsDrK6FdRfpFVgC4UodAZqgig6WoVmg5SxoY5rGvvTEyzUoam5xP3wwPXbZEvvnznlyA8Iy1hiEa2zUtLCKTmfzSidE6rM6kKbw65Nu9nXZIZZg8uq22QPqEkQyIdO6/MNXRrAB9Av8sPJzKXd6dRUlNjRRpjXYORYV2gqYX3LnVn1GTs9vaExNVrs97pKjT0QFXdxM9wPE52cO+gnIfDj/6yxl+0d62YllI9FfkFfCG2Z0GGIhtMOd3yI2x1m4EO55KCXMRrVinp7OChy395ADuii56BuaqKDpbssB4zwLwUmQBdVaUKJc6H1ZwcqEalZITSzmJ9qNiVMBLXgFXbeneAVHLcq2Rhcu6SqaQLz1mdTnqgfpoEJmgLVHB/wtqTuCf0hBcC6wvBstnLKnnoF+MJeoVlR8Yn3DxET/r94wmC9x97kG/H4Slnlx4R6udd6a+1XLXtiowGJwbvaKMp5rqmRqiZTnjUFoB+kQona0Sf56PK8pXOTcLmkBnuffw4YjJLd+tSl5tdBdkh54jJfeNz1JwDsB2UW8rde+uriy323V1bjtAx3qBq//9Ypl1zdAQO1MnA=
  - secure: B3ALVlkWFPObF9z3qm0nBaPAo6Ogc1ehbDUgzwh2zR6yEwU5o505xKMV8hgf/DBywW1i+5l8xG0jj9W+ZT4nQG9edF2/HOw2hHspM1W4AB56oFrhfztkgqF+UaO5rtn5VYNXg3H5ok/zt+9cLhLQWvuseLzPZmd/HhSzbWG3FIuzYCPQdbxuiMs1YEgmsB6mvSBPOCJKKSYiKizpEh76ed4nARszRWA3q10vPGWC/6E2VTnE9yKokliB43amCtsPVNN55CfTde/QLBfmJD8MdTay+jlOuilHBfROF3Nm5b9Js5Opy4IxYMg+4O77C9YXNdJSZwmE36wOnI8PEiYjoaZ2hbSzqgZg7zwyzT73DE+U07uiK8+R+7yq3s6gjrWSt92MPmT7eecECYix04wrtYhrhFWzRRAHHjJWkHJfussbva9Z9liyKqEMLjx8GmNKM9v4VgUZq73iq/rlkHt8eNip2wrvboEyouRuUG/WKaaVhEnBwZ6JHJMobqwi7DZAzNGerHaTZW/vl2SZrO3GU5VCca4b6wH2E8wTD7ij4K24FOwbBs6FcE1qJbAUzA3O4vhBDPeGkEh/fi8q6ppmCb16/OngE9JvBmkqyMTgow1ij7N1bAYGoox14X6TXNxtcBtX8RrL+Wqfz4f4zgygwmrea0CacOL6cuXZPUZm4zM=
  - secure: sHwvaSkBpfvhWaYDWZ3Ru2VuH0fo1+F2l8T5rP1repRQiaIravk6gSWjsFiPIDyuP+EkR2DE+PTXpEAzWPXxmUi8Zcmm9iUCaZzodP8Y6X8XOopKZ3LUp8tS5+5L52UuuxwOFxl+/ke/rQ4pwZIiicp1oc85jQJR12wNuBl95tTWPiiNIQn1XOIxyBQsd6tKMApfNJjDu6sCwAPZ8EAhDtj5bPKZ5WIIVmOoRSiRxGAF1NpCxbVmRGFRE5xiXWvcYIk1J+6u79u92NBxyPYhqPdUw/H0XHVY3ovsWHPzWh7/tF2YwWb7D6rwKSBJ9rAHeUIbcgizAjrAXHy6InB36BydXfWaNN9il/QP37lOsY5fPb0//ge1qN+fKYQCq/3zQfsqHk84yRR5i1bQAguhE015RpH6yf/eK6aXej8fBBGb+CbAtDBq2ZohDTUkIF6yIgQJVts79VEgqzP2LA6kROSEnLg0hYwux1XpyOBSIelSAZeEY/sWcAEIwL+s9JwovX/ED4OvOtzZXNEJjxeDFLm9H6NypQ+JguhUrFBfhUcxd+iQ8xv57JWmwbQ8LKLHAbcV1J5ecVwCZkmC2url6iYv/1Hmga7uHFZcSyIsRmYhkGiYKTyK/lN4V6ZsztwCkS1tk/sjeRSl0Vf2Z/g1vkLiNDeb//aU6ZtbgGqPBfg=
  - secure: VnOZu0UibfJkpG3z6GrhAVpCyd2eiqKI+3mx/LNMlIHKVoExzK4IR+YbF3Rb4ff+c+0pv/FqF6ZZ1mzM3DfZ7S0uj7QOG49Ge14HY2ap9Ea/OopZ8akqsRqKNe4oqtdkZ7HN6EgLSG7XnBtZBLWfvCRnKl0VyCehnYVEoUpG9s5exqlHa6gneph260yNILC4S8OaqJ9eQdddrpWr2OQUvDkD5pg8VFBJefjX5/RzqAwDI1drruvc+pAXbVmrqCk3EBRI0HeKhtwtyHvaTCz5/4s3curxZBngqajm106H7jBL6hUp2iIqpQDMtD6/w7ksniweHuEDnz1/oYfHmFaaHa9p0SUaq7NugvlqvABmnEBV4ZrRt3GTs/uuACQCiRqPWQarBhzPfLgNIiaJWk95PyjJvgpFcxoYxwVZ8Ow9H63VeYYfYXYE7lBkVZrEDzqsPGVNOkndpLXHnsfrin1XvalotXuQZ9/Vs9iFHdMO3Pfn+mrzR1Mx6Qd3WGETCqIvCvqjN1VzloHHy9BjDt3kCdohmhSLTHMv94soQ2zXAQg3r9jmPzFrfDKTZHF+aD0WqBES/DURnYHvZs6n7iOBnsyn9dW96vjgaCxf8upGBuc+Z8Ot82CBrDiwqWkTjaoQjUv6su9x5o4W0GIsyGdLDYZHreL7BKjjGHFMLb3jnSA=

r_github_packages:
- DeclareDesign/DDtools

after_success:
- Rscript -e DDtools::after_build

