// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// block_assign_cpp
IntegerVector block_assign_cpp(IntegerVector block_int, IntegerVector m_given, NumericVector prob_b, int mode);
RcppExport SEXP _randomizr_block_assign_cpp(SEXP block_intSEXP, SEXP m_givenSEXP, SEXP prob_bSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type block_int(block_intSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m_given(m_givenSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob_b(prob_bSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(block_assign_cpp(block_int, m_given, prob_b, mode));
    return rcpp_result_gen;
END_RCPP
}
// block_assign_multi_cpp
IntegerVector block_assign_multi_cpp(IntegerVector block_int, NumericMatrix param, int mode);
RcppExport SEXP _randomizr_block_assign_multi_cpp(SEXP block_intSEXP, SEXP paramSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type block_int(block_intSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type param(paramSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(block_assign_multi_cpp(block_int, param, mode));
    return rcpp_result_gen;
END_RCPP
}
// cube_two_arm_cpp
NumericVector cube_two_arm_cpp(NumericVector p, IntegerVector b, IntegerVector ord, double tol);
RcppExport SEXP _randomizr_cube_two_arm_cpp(SEXP pSEXP, SEXP bSEXP, SEXP ordSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_two_arm_cpp(p, b, ord, tol));
    return rcpp_result_gen;
END_RCPP
}
// cube_multi_cpp
NumericMatrix cube_multi_cpp(NumericMatrix P, IntegerVector b, IntegerVector ord, double tol);
RcppExport SEXP _randomizr_cube_multi_cpp(SEXP PSEXP, SEXP bSEXP, SEXP ordSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ord(ordSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cube_multi_cpp(P, b, ord, tol));
    return rcpp_result_gen;
END_RCPP
}
