# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

block_assign_cpp <- function(block_int, m_given, prob_b, mode) {
    .Call('_randomizr_block_assign_cpp', PACKAGE = 'randomizr', block_int, m_given, prob_b, mode)
}

