# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

block_assign_cpp <- function(block_int, m_given, prob_b, mode) {
    .Call('_randomizr_block_assign_cpp', PACKAGE = 'randomizr', block_int, m_given, prob_b, mode)
}

block_assign_multi_cpp <- function(block_int, param, mode) {
    .Call('_randomizr_block_assign_multi_cpp', PACKAGE = 'randomizr', block_int, param, mode)
}

cube_two_arm_cpp <- function(p, b, ord, tol) {
    .Call('_randomizr_cube_two_arm_cpp', PACKAGE = 'randomizr', p, b, ord, tol)
}

cube_multi_cpp <- function(P, b, ord, tol) {
    .Call('_randomizr_cube_multi_cpp', PACKAGE = 'randomizr', P, b, ord, tol)
}

cube_on_x_cpp <- function(p, X, tol) {
    .Call('_randomizr_cube_on_x_cpp', PACKAGE = 'randomizr', p, X, tol)
}

